apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: ubuntu
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
        command: ["/bin/sh"]
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-service
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
